# Generated by Django 3.2.6 on 2022-09-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
