# Generated by Django 4.1.1 on 2022-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_auto_20220922_2318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Введите время создания объявления",
                null=True,
                verbose_name="Время создания объявления",
            ),
        ),
    ]
