# Generated by Django 4.1.1 on 2022-09-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_comment_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ads.ad"
            ),
        ),
    ]
