# Generated by Django 4.1.1 on 2022-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20220922_2323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                help_text="Укажите, активен ли аккаунт",
                null=True,
                verbose_name="Аккаунт активен",
            ),
        ),
    ]
