# Generated by Django 4.1.1 on 2022-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя, максимально 50 символов",
                max_length=50,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Введите имя, максимально 50 символов",
                max_length=50,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Укажите телефон для связи",
                max_length=25,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
